Spark.create!([
  {name: "Pyre", flavor: "The first scouts returned from the scourged darkness of the Dusk telling stories of monstrous beasts and horrific cults, and humanity created something to hunt them: the Pyre. Where before we had to run when denizens of the Dusk would get near, now we could take the fight to them.", description: "As a Pyre, you deal strong single-target damage, complimented by high mobility. You have the right trick for every situation, so long as it calls for violence."},
  {name: "Scorch", flavor: "As our grasp of sunwell tech expanded, so did our Sparks. Armed with multiple sun shards, the Scorch is the embodiment of our dead sun’s fury. Conjuring flames with the flick of a wrist, the Scorch is a necessity for pushing back against the encroaching Dusk.", description: "As a Scorch, you to set the battlefield on fire. While your primary goal is to burn out your enemies, you help the team stay fueled up, and ready to fight."},
  {name: "Voyager", flavor: "The first Spark ever created, the Voyager is designed for quick movement and stealth, built for reconnaissance and scouting missions. The Dusk is a constantly shifting abyss, and without the Voyagers, we wouldn’t have a clue what we were dealing with. It takes a special soul to want to walk into the unknown.", description: "As a Voyager, you support your squad by marking enemies, allowing you and your allies to devastate them. The Voyager manipulates and controls the battlefield in lieu of all-out damage."},
  {name: "Warden", flavor: "Larger caravans and Spark teams bring the attention of the worst in the Dusk. The Warden protects anyone in their retinue, smashing the enemies of humanity into dust. Pilots of Wardens know that they must put themselves between the horrors of the Dusk, and those they’ve sworn to protect. They do so proudly.\n  ", description: "As a Warden, you’re defender and a bully on the battlefield. You help allies to endure incoming damage, while charging across the Dusk, ready to shout out a challenge to those who would harm your friends."},
  {name: "Pox", flavor: "The Pox uses what humanity has learned of plague and viruses and weaponizes it against the Dusk. Capable of rapidly spreading, evolving, and activating various contagious elements, these Sparks are reserved for our most formidable foes. The methods are questionable, but nobody can question their effectiveness.\n  ", description: "As a Pox, your goal is to infect as many enemies in the fight as possible, steadily damaging them. Once you have a sufficient number under the influence of your miasma, you unleash potent effects, even activating a fight or flight response."},
  {name: "Grim", flavor: "The science behind the Grim Spark is a closely kept secret. Out in the field, this Spark appears to be able to reanimate and puppeteer the recently deceased. Given its controversial capabilities, this Spark isn’t deployed lightly. Pilots who choose a Grim Spark understand that doing so comes with a reputation, and one that many of them are more than happy to embrace.\n  ", description: "As a Grim, you to raise the dead, enthralling them to you. Pull their strings and send your thralls lashing out at enemies, while summoning a chorus of bone-chilling screams."},
  {name: "Sanguine", flavor: "Sparks are able to regularly refuel in the Dusk by breaking down their enemies, but only one can completely repair themselves. The Sanguine Spark drains the lifeforce from those out in the Dusk, ripping it from their bodies and using it to fuel their own macabre powers. Just... no more vampire jokes, they’ve heard them all already.\n  ", description: "As a Sanguine, you toe the line between supporting your fellow squad mates and dealing devastating damage with your blood blade. You rest easy knowing that your Spark will always come back with a blood-fueled fury."},
  {name: "Infernal", flavor: "For most of us, the nova event was the end of the world. But a new Spark is heralding a new end of days. Infernal is a cursed amalgamation of technology and the arcane. Nobody is sure where Infernal came from. One day, the sky was red for a brief moment, a respite from the constant hazy darkness, and then Infernal walked out from the Dusk.", description: "As an Infernal, you will lockdown the battlefield, condemning the denizens of the Dusk as you do so. Fire and brimstone surround you, and those who suffer your attention will find themselves unable to harm you, the damned souls that they are."},
  {name: "Drifter", flavor: "As technology of old earth was uncovered and researched, it was melded with the new power of the sun shards. The Drifter Spark’s firearms launch bolts of fiery sunlight, and they bring an arsenal with them to adapt to any combat scenario. Few Sparks can match the Drifter’s versatility for dealing death.", description: "As a Drifter, you’re effective in many different situations, but rely on your ability to position yourself in a fight to use your strengths. A jack of all trades is a master of none, and so you must learn what kind of deadeye you want to be, or that your squad needs."}
])
Passive.create!([
  {name: "Slash", description: "Lash out with your solar blade. Deal 1 Harm to a Close enemy at the start of your turn.", spark_id: 1},
  {name: "Controlled Burn", description: "Warp the resources of your enemies. Once per GM turn, you can change a drop from one type to the other (e.g. Health to Fuel).", spark_id: 2},
  {name: "Marked", description: "Using your advanced tracking system, find your foes. At the start of your turn, Mark any two enemies. Marks remain until they have been used, but do not stack.", spark_id: 3},
  {name: "Unstoppable", description: "Foes are shaken by your very presence. While moving, stun 1 enemy within Close range, they cannot act for the rest of the round.", spark_id: 4},
  {name: "Virulent", description: "Your plauge slowly destroys all. Infect 1 enemy at the start of combat. Enemies who are Infected take 1 Harm at the start of your turn.", spark_id: 5},
  {name: "Raise Dead", description: "Once per round, when an enemy dies, you may immediately make them your Thrall. Thralls are revived with 1 Health and act with your Powers. Thralls cannot move unless a mod allows it. You may have a number of Thralls equal to your Shade.", spark_id: 6},
  {name: "Empty Clip", description: "Pull out the big guns when things look tough. If you have 0 Fuel at the end of your turn, you may activate your Supernova. Gain 3 Fuel after.", spark_id: 9},
  {name: "Blood Born", description: "Your blood is just another resource to you. You may spend 1 Health when using a Power to activate its Blood effect.", spark_id: 7},
  {name: "Damnation", description: "Enemies affected by your Powers are Damned. Damned enemies deal +1 Harm the next time they attack a Spark, and then inflict double that Harm on themselves. Damned is removed after.", spark_id: 8}
])
ActivePower.create!([
  {name: "Dash", description: "Single out your target and charge them down. Deal 2 Harm to an enemy at Close range, or 3 Harm to them if you moved before activating Dash.", spark_id: 1},
  {name: "Singe", description: "Cast a fiery arc with your solar blade. Deal 1 Harm to all enemies within Close range.", spark_id: 1},
  {name: "Finisher", description: "Streak across the ground like wildfire, dealing 1 Harm to every injured enemy within Near range of you.", spark_id: 1},
  {name: "Tracer Round", description: "Hurl a flaming spear at a Far enemy, dealing 1 Harm. At the start of the next round, you can instantly teleport next to that enemy.", spark_id: 1},
  {name: "Engulf", description: "Your Spark is wreathed in flame. Until the end of your next turn, any Close enemies take 2 Harm.", spark_id: 2},
  {name: "Erupt", description: "Columns of flame burst from the ground. Deal 2 Harm to target within Near range, and 1 Harm to anyone Close to them.", spark_id: 2},
  {name: "Snuff Out", description: "Focus the sun’s fury on a wounded foe. Target injured enemy at any range takes Harm equal to your Shade.", spark_id: 2},
  {name: "Kindling", description: "Fire shards of sun in all directions. Choose a number of targets equal to or less than your Sun, at any range. Enemies take 1 Harm, allies recover 1 Health or Fuel.", spark_id: 2},
  {name: "Seek", description: "Micro-explosives are sent hurtling through the air. Choose 1 Marked enemy. They take +1 Harm from all sources until the start of the next round. Target lose Mark.", spark_id: 3},
  {name: "Destroy", description: "Fire a salvo of homing explosives. Every Marked enemy takes 2 Harm. Targets lose Mark.", spark_id: 3},
  {name: "Holospark", description: "Deploy a decoy Spark at up to Near range. Marked enemies will target the decoy. HoloSpark ends at the end of the round. Affected enemies lose Mark.", spark_id: 3},
  {name: "Swap", description: "Feel the quantum pull as your suit begins to phase. Switch positions with a marked enemy within Near or Far range. Target loses Mark.", spark_id: 3},
  {name: "Bulwark", description: "Slam down an extending shield. You and all Close allies reduce enemy Harm by 1 until the end of the round.", spark_id: 4},
  {name: "Rush", description: "Charge forward as an unstoppable force. Choose a Near location and rush towards it. Deal 1 Harm to any enemy in your way. This does not replace your movement.", spark_id: 4},
  {name: "Crush & Throw", description: "Target Close enemy is crushed in your grip for 2 Harm, and then can be thrown to a Near location. Any enemies there take 1 Harm.", spark_id: 4},
  {name: "Over Here", description: "Recover Health equal to your Sun score as you roar out a challenge to your foes. All Near enemies must attack you until the start of your next turn.", spark_id: 4},
  {name: "Infect", description: "Cast forth a plague bomb. Infect 1 enemy within Near range.", spark_id: 5},
  {name: "Spread", description: "Compel the plague to spread far and wide. Target an Infected enemy up to Near range. Infect all enemies within Close range of target.", spark_id: 5},
  {name: "Symptomatic", description: "Decide the fate of the infected. Choose one effect for all Infected enemies this round: -1 Harm dealt, +1 Harm taken, or cannot Move.", spark_id: 5},
  {name: "Fight or Flight", description: "Disease can cause unpredictable behavior. Every Infected enemy either immediately deals their Harm to closest enemy, or runs away from you for one round, GM’s choice.", spark_id: 5},
  {name: "Pull Strings", description: "Command your Thralls to lash out. Target Thrall attacks a Close enemy, dealing its Harm.", spark_id: 6},
  {name: "Siphon", description: "Sacrifice a Thrall within Close range. It creates drops of Health or Fuel equal to its maximum Health. Any ally may claim them.", spark_id: 6},
  {name: "Possess", description: "Deal two Harm to an enemy within Near range, and give them a single command that they must obey.", spark_id: 6},
  {name: "Haunt", description: "All Thralls shriek into the air. Any enemies within Close range to them recoil in fear and cannot act during GM’s turn.", spark_id: 6},
  {name: "Fan the Hammer", description: "Fire off a flurry of shots in the blink of an eye. Choose Close targets equal to current Fuel count. Each target takes 1 Harm.", spark_id: 9},
  {name: "Hip-Fire", description: "Your shot has the sun’s fury behind it. Deal Harm equal to Sun to target within Near range.", spark_id: 9},
  {name: "Duel", description: "Single out your foe and challenge them. Choose an enemy at up to Near range. Deal damage equal to Moon. If the enemy survives, inflict their Harm to yourself.", spark_id: 9},
  {name: "Take Aim", description: "Take aim at those who think they are safe from you. Deal Harm equal to Shade to 1 enemy at Far range, or 1 Harm to a number of Far enemies equal to your Shade.", spark_id: 9},
  {name: "Transfusion", description: "Life, like all things, can be traded away. Choose two targets Close to each other. Transfer 1 Health from one to the other. Blood effect: Transfer Health equal to your Sun instead.", spark_id: 7},
  {name: "Siphon", description: "Pull the lifeforce right from your foes. Deal 1 Harm to one Enemy within Close range and gain 1 Health. Blood effect: Affects all Close enemies.", spark_id: 7},
  {name: "Blood Blade", description: "Lash out with whirling talons made of your own blood. Lose 1 Health and deal 1 Harm to every enemy within Close range. Blood effect: Deal Harm equal to your Shade instead.", spark_id: 7},
  {name: "Cauldron", description: "Burst into a swarm of bats and move to any location within Far range. Deal 1 Harm to all Close enemies at location. Blood effect: Deal Harm equal to your Moon.", spark_id: 7},
  {name: "Hellfire", description: "Ignite an enemy’s soul with a touch. Deal 3 Harm to an enemy within Close range. If they die from Hellfire, they explode and deal 1 Harm to all enemies within Close range to them.", spark_id: 8},
  {name: "Brimstone", description: "Rock and ash burst from a tear in the ground. Deal 1 Harm to an enemy within near range, and all enemies within Close range to your target. All damaged enemies can only attack at Close range until the end of the round.", spark_id: 8},
  {name: "Banish", description: "Cast your enemy to a realm of fire and pain, momentarily. One enemy within Close range disappears from the battle. They return at the end of your next turn.", spark_id: 8},
  {name: "Sinner's Snare", description: "Bind the bodies of your closest foes, and damn their souls. Target a number of enemies equal to Moon, they cannot act this round.", spark_id: 8}
])
Supernova.create!([
  {name: "Firestorm", description: "Choose a single enemy at any range. Move to Close range and deal Harm equal to your Sun + Moon.", spark_id: 1},
  {name: "Glory & Flame", description: "Two waves blast off of you, one wrathful, one radiant. All damaged enemies immediately take Harm equal to your Sun. Allies recover Health equal to your Shade.", spark_id: 2},
  {name: "SOS Salvo", description: "Fire off a solar shard for each point of Moon you have. Shards can hit any range, and deal 2 Harm each.", spark_id: 3},
  {name: "Earthquake", description: "Send a shock wave through the ground. Target a number of enemies equal to your Sun and deal 2 Harm. Targets are stunned for the rest of the round.", spark_id: 4},
  {name: "Patient Zero", description: "All Infected enemies take Harm equal to the number of Infected enemies. Infection for everyone is then removed.", spark_id: 5},
  {name: "Death Curse", description: "Your Thralls detonate with their death curse. Each deals 2 Harm to all enemies within Close range.", spark_id: 6},
  {name: "Bullet Hell", description: "Fill the air with bullets of sunlight. Choose a range. Every enemy at that range takes 2 Harm.", spark_id: 9},
  {name: "Undead", description: "You lock down, surrounding yourself with a steel coffin. No effect on death. You resurrect at the start of the next round without requiring aid from an ally. Activate Siphon when you do. Doing this uses your action, and you may only Move on your turn.", spark_id: 7},
  {name: "Final Judgement", description: "All enemies within Close range are dragged down to Hell and killed.", spark_id: 8}
])
PersistentMod.create!([
  {name: "Fury", description: "+1 Sun", spark_id: 1},
  {name: "Fury", description: "+1 Sun", spark_id: 1},
  {name: "Cool", description: "+1 Shade", spark_id: 1},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 1},
  {name: "Hardy", description: "+1 Health", spark_id: 1},
  {name: "Hardy", description: "+1 Health", spark_id: 1},
  {name: "Mercury", description: "Move twice per turn.", spark_id: 1},
  {name: "Honed", description: "+1 Harm to Slash.", spark_id: 1},
  {name: "Quick-Strike", description: "Slash can target two enemies.", spark_id: 1},
  {name: "Retaliate", description: "Slash activates every time you take Harm, as well as at the start of your turn.", spark_id: 1},
  {name: "Fury", description: "+1 Sun", spark_id: 2},
  {name: "Cyclical", description: "+1 Moon", spark_id: 2},
  {name: "Cool", description: "+1 Shade", spark_id: 2},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 2},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 2},
  {name: "Hardy", description: "+1 Health", spark_id: 2},
  {name: "Sun Burst", description: "You may have 1 drop each round explode, dealing 2 Harm to all Close enemies.", spark_id: 2},
  {name: "Light Up", description: "You can change 2 drops per GM Turn instead of 1.", spark_id: 2},
  {name: "Adaptive", description: "Any drop you pick up can be treated as Health or Fuel.", spark_id: 2},
  {name: "Bountiful", description: "Enemies you kill create 2 drops during the GM Turn.", spark_id: 2},
  {name: "Cyclical", description: "+1 Moon", spark_id: 3},
  {name: "Cyclical", description: "+1 Moon", spark_id: 3},
  {name: "Cool", description: "+1 Shade", spark_id: 3},
  {name: "Cool", description: "+1 Shade", spark_id: 3},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 3},
  {name: "Hardy", description: "+1 Health", spark_id: 3},
  {name: "Sonar", description: "You may Mark any three enemies instead of two.", spark_id: 3},
  {name: "Studied", description: "Marked enemies deal -1 Harm to you.", spark_id: 3},
  {name: "Stun", description: "At start of turn, choose 1 Marked enemy to not act this round.", spark_id: 3},
  {name: "Nitro", description: "Can take one extra non-Power action each turn.", spark_id: 3},
  {name: "Fury", description: "+1 Sun", spark_id: 4},
  {name: "Fury", description: "+1 Sun", spark_id: 4},
  {name: "Cool", description: "+1 Shade", spark_id: 4},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 4},
  {name: "Hardy", description: "+1 Health", spark_id: 4},
  {name: "Hardy", description: "+1 Health", spark_id: 4},
  {name: "Defiant", description: "Regain 1 Health at the start of your turn.", spark_id: 4},
  {name: "Shockwave", description: "Stun 2 total enemies with Unstoppable.", spark_id: 4},
  {name: "Sweep", description: "If you don't Move, all Close enemies cannot act this round.", spark_id: 4},
  {name: "Ramming", description: "Enemies hit by Unstoppable take 2 total Harm.", spark_id: 4},
  {name: "Fury", description: "+1 Sun", spark_id: 5},
  {name: "Cyclical", description: "+1 Moon", spark_id: 5},
  {name: "Cool", description: "+1 Shade", spark_id: 5},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 5},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 5},
  {name: "Hardy", description: "+1 Health", spark_id: 5},
  {name: "Deadly", description: "Virulent deals 2 total Harm to Infected.", spark_id: 5},
  {name: "Plague Bringer", description: "Virulent Infects 3 enemies instead.", spark_id: 5},
  {name: "Vector", description: "Once per round, Infect an enemy within Close range.", spark_id: 5},
  {name: "Evolved", description: "Choose one of the Symptomatic effects to permanently be in effect for all Infected. This effect can no longer be chosen when using Symptomatic.", spark_id: 5},
  {name: "Fury", description: "+1 Sun", spark_id: 6},
  {name: "Cyclical", description: "+1 Moon", spark_id: 6},
  {name: "Cool", description: "+1 Shade", spark_id: 6},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 6},
  {name: "Hardy", description: "+1 Health", spark_id: 6},
  {name: "Builder", description: "+1 Thrall Health", spark_id: 6},
  {name: "Sewn Sinew", description: "Thralls are revived with Sun Health, up to their max Health.", spark_id: 6},
  {name: "Enthralling", description: "Can make a Thrall anytime an enemy dies, not just once per round.", spark_id: 6},
  {name: "Danse Macabre", description: "One Thrall can move during your turn as well.", spark_id: 6},
  {name: "Howlers", description: "Whenever a Thrall dies for any reason, they activate the Haunt effect at their location.", spark_id: 6},
  {name: "Fury", description: "+1 Sun", spark_id: 9},
  {name: "Cyclical", description: "+1 Moon", spark_id: 9},
  {name: "Cool", description: "+1 Shade", spark_id: 9},
  {name: "Leak", description: "-1 Fuel", spark_id: 9},
  {name: "Leak", description: "-1 Fuel", spark_id: 9},
  {name: "Hardy", description: "+1 Health", spark_id: 9},
  {name: "Smaller Tank", description: "Gain 2 Fuel from Empty Clip.", spark_id: 9},
  {name: "Blood Bullets", description: "May treat Fuel drops as Health drops instead.", spark_id: 9},
  {name: "Mercury", description: "May move twice per turn.", spark_id: 9},
  {name: "Bullet Storm", description: "Supernova deals 4 Harm instead of 2.", spark_id: 9},
  {name: "Fury", description: "+1 Sun", spark_id: 7},
  {name: "Cyclical", description: "+1 Moon", spark_id: 7},
  {name: "Cool", description: "+1 Shade", spark_id: 7},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 7},
  {name: "Hardy", description: "+1 Health", spark_id: 7},
  {name: "Hardy", description: "+1 Health", spark_id: 7},
  {name: "Hearty", description: "Recover 2 Health from drops.", spark_id: 7},
  {name: "Leech", description: "Fuel drops also provide 1 Health.", spark_id: 7},
  {name: "Reborn", description: "Gain the Blood effect from Siphon with your Supernova.", spark_id: 7},
  {name: "Mobile Grave", description: "You may resurrect anywhere within Near of where you died.", spark_id: 7},
  {name: "Fury", description: "+1 Sun", spark_id: 8},
  {name: "Cyclical", description: "+1 Moon", spark_id: 8},
  {name: "Cool", description: "+1 Shade", spark_id: 8},
  {name: "Wellspring", description: "+1 Fuel", spark_id: 8},
  {name: "Hardy", description: "+1 Health", spark_id: 8},
  {name: "Hardy", description: "+1 Health", spark_id: 8},
  {name: "Eternal", description: "Damnation is not removed after enemies deal Harm. The Damnation effect does not stack if they are affected by another Power.", spark_id: 8},
  {name: "Dance with the Devil", description: "Damned enemies take 1 Harm whenever they are Close to you.", spark_id: 8},
  {name: "Fine Print", description: "Damned enemies cannot deal Harm to you.", spark_id: 8},
  {name: "Toll", description: "Damned enemies are affected by Final Judgement, at any range.", spark_id: 8},
])
PowerMod.create!([
  {name: "Finder", description: "+1 Range", spark_id: 1},
  {name: "Lethal", description: "+1 Harm", spark_id: 1},
  {name: "Lethal", description: "+1 Harm", spark_id: 1},
  {name: "Efficient", description: "Costs no fuel", spark_id: 1},
  {name: "Prepped", description: "First time this power is used in combat, it doesn't count as an action.", spark_id: 1},
  {name: "Overclock", description: "Spend 1 extra Fuel to double the Harm.", spark_id: 1},
  {name: "Sweep", description: "Dash affects all enemies Close to target as well.", spark_id: 1},
  {name: "Lit", description: " Enemies hit by Singe take 1 Harm if they act that round.", spark_id: 1},
  {name: "Phase-Shift", description: "Harm for Finisher equals Moon instead of 1.", spark_id: 1},
  {name: "Pinned", description: "Target of Tracer Round cannot act this round.", spark_id: 1},
  {name: "Finder", description: "+1 Range", spark_id: 2},
  {name: "Lethal", description: "+1 Harm", spark_id: 2},
  {name: "Lethal", description: "+1 Harm", spark_id: 2},
  {name: "Lethal", description: "+1 Harm", spark_id: 2},
  {name: "Efficient", description: "Costs no fuel", spark_id: 2},
  {name: "Colder", description: "May use any Attribute in place of another.", spark_id: 2},
  {name: "Expel", description: "When Engulf ends, it explodes outward, dealing 1 Harm to every enemy up to Near.", spark_id: 2},
  {name: "Wall of Fire", description: "Erupt's column remains in place for a number of rounds equal to your Moon. Deals 1 Harm to anyone that gets Close to it.", spark_id: 2},
  {name: "Siphon", description: "If Snuff Out target dies, you regain 1 Fuel.", spark_id: 2},
  {name: "Stockpile", description: "Number of Kindling targets equals current amount of Fuel.", spark_id: 2},
  {name: "Finder", description: "+1 Range", spark_id: 3},
  {name: "Lethal", description: "+1 Harm", spark_id: 3},
  {name: "Efficient", description: "Costs no fuel", spark_id: 3},
  {name: "Prepped", description: "First time this power is used in combat, it doesn't count as an action.", spark_id: 3},
  {name: "Tagged", description: "This Power does not use target's Mark.", spark_id: 3},
  {name: "Tagged", description: "This Power does not use target's Mark.", spark_id: 3},
  {name: "Lockdown", description: "Seek target cannot act this round.", spark_id: 3},
  {name: "Splash", description: "Enemies within Close range to Destroy targets take 1 Harm.", spark_id: 3},
  {name: "Hardlight Holo", description: "HoloSpark explodes at the end of round, dealing 1 Harm to all Close enemies and Marking them.", spark_id: 3},
  {name: "Matchmaker", description: "You can switch the target with an ally instead of yourself.", spark_id: 3},
  {name: "Finder", description: "+1 Range", spark_id: 4},
  {name: "Finder", description: "+1 Range", spark_id: 4},
  {name: "Lethal", description: "+1 Harm", spark_id: 4},
  {name: "Lethal", description: "+1 Harm", spark_id: 4},
  {name: "Efficient", description: "Costs no fuel", spark_id: 4},
  {name: "Prepped", description: "First time this power is used in combat, it doesn't count as an action.", spark_id: 4},
  {name: "Reflective", description: "Deal 1 harm to enemies that attack allies protected by Bulwark.", spark_id: 4},
  {name: "Courier", description: "You may carry a Close ally with you when using Bull.", spark_id: 4},
  {name: "Pull Pin", description: "Enemies killed by Crush & Throw explode upon impact, dealing a total of 3 Harm to enemies there.", spark_id: 4},
  {name: "Intimidation", description: "You may have non-Elite enemies flee from you instead of attack you when using Over Here.", spark_id: 4},
  {name: "Finder", description: "+1 Range", spark_id: 5},
  {name: "Finder", description: "+1 Range", spark_id: 5},
  {name: "Efficient", description: "Costs no fuel", spark_id: 5},
  {name: "Prepped", description: "First time this power is used in combat, it doesn't count as an action.", spark_id: 5},
  {name: "Split Mind", description: "+1 targets", spark_id: 5},
  {name: "Split Mind", description: "+1 targets", spark_id: 5},
  {name: "Adrenal", description: "Infected target has the Fight or Flight effect immediately.", spark_id: 5},
  {name: "Viral Link", description: "Spread target takes Harm equal to number of newly Infected enemies.", spark_id: 5},
  {name: "Clouded", description: "New effect option for Symptomatic: Enemies can only deal Harm within Close range.", spark_id: 5},
  {name: "Dual Strand", description: "Enemies have both effects from Fight or Flight.", spark_id: 5},
  {name: "Finder", description: "+1 Range", spark_id: 6},
  {name: "Finder", description: "+1 Range", spark_id: 6},
  {name: "Efficient", description: "Costs no fuel", spark_id: 6},
  {name: "Prepped", description: "First time this power is used in combat, it doesn't count as an action.", spark_id: 6},
  {name: "Split Mind", description: "+1 targets", spark_id: 6},
  {name: "Split Mind", description: "+1 targets", spark_id: 6},
  {name: "Weaver", description: "A number of Thralls equal to your Shade or fewer may act with Pull Strings.", spark_id: 6},
  {name: "Ritualistic", description: "Thralls sacrificed with Siphon curse enemies within Close range. Cursed enemies take +1 Harm or deal -1 Harm until your next turn, your choice.", spark_id: 6},
  {name: "Horrified", description: "All enemies within Close range of Possess target take 1 Harm and cannot move this round.", spark_id: 6},
  {name: "Rallying Cry", description: "One ally within Close range of Haunted Thralls may take another turn this round.", spark_id: 6},
  {name: "Overclock", description: "Spend 1 extra Fuel to double the Harm.", spark_id: 9},
  {name: "Overclock", description: "Spend 1 extra Fuel to double the Harm.", spark_id: 9},
  {name: "Solar", description: "Uses Sun Instead.", spark_id: 9},
  {name: "Lunar", description: "Uses Moon Instead.", spark_id: 9},
  {name: "Twilight", description: "Uses Shade Instead.", spark_id: 9},
  {name: "Prepped", description: "First time this power is used in combat, it doesn't count as an action.", spark_id: 9},
  {name: "Hammer Forged", description: "Fan the Hammer Harm equals current Fuel count.", spark_id: 9},
  {name: "Explosive", description: "Hip Fire deals Harm to all enemies Close to target as well.", spark_id: 9},
  {name: "Deadeye", description: "Once per round, if you kill the target with Duel, you may immediately Duel again at no cost.", spark_id: 9},
  {name: "Ricochet", description: "If single target for Take Aim dies, deal Harm equal to your Shade to an enemy within Close range of the target.", spark_id: 9},
  {name: "Finder", description: "+1 Range", spark_id: 7},
  {name: "Lethal", description: "+1 Harm", spark_id: 7},
  {name: "Lethal", description: "+1 Harm", spark_id: 7},
  {name: "Efficient", description: "Costs no fuel", spark_id: 7},
  {name: "Prepped", description: "First time this power is used in combat, it doesn't count as an action.", spark_id: 7},
  {name: "Blood Soaked", description: "Gain Blood effect at no Health cost.", spark_id: 7},
  {name: "Donor", description: "You and allies gain double Health from Transfusion.", spark_id: 7},
  {name: "Refreshing", description: "If you kill with Siphon, you may immediately activate another Power. You must still pay the Fuel to do so.", spark_id: 7},
  {name: "Honed Blood", description: "Lose any number of Health to deal that number of Harm with Blood Blade.", spark_id: 7},
  {name: "War Path", description: "Cauldron deals 1 Harm to all enemies in the movement path.", spark_id: 7},
  {name: "Finder", description: "+1 Range", spark_id: 8},
  {name: "Lethal", description: "+1 Harm", spark_id: 8},
  {name: "Lethal", description: "+1 Harm", spark_id: 8},
  {name: "Efficient", description: "Costs no fuel", spark_id: 8},
  {name: "Split Mind", description: "+1 targets", spark_id: 8},
  {name: "Split Mind", description: "+1 targets", spark_id: 8},
  {name: "White Hot", description: "Explosion Harm for Hellfire equals your Sun.", spark_id: 8},
  {name: "Fissure", description: "Brimstone now affects a line between you and a Far location.", spark_id: 8},
  {name: "Rift Tear", description: "When Banish Target returns, they deal Harm equal to your Shade to all enemies Close to their location.", spark_id: 8},
  {name: "Bind Them", description: "Damned enemies affected by Sinner's Snare take 1 Harm in addition to the Power's effects.", spark_id: 8},
])